### PR TITLE
Updates to the Readme.md file

### PR DESCRIPTION
**Pull request by rowtechshio**
## Changelog

-Re-wrote the introduction to be more inviting and explanatory
-Added three new pixel animations, one of which was captured by me from Starbound
-Added "Starbound" and "To the Moon/Finding Paradise" to the Inspiration->Games section under the correct release date order
-Added 3 new Vimeo videos to the Inspiration->Videos section
-Reorganized the Readme into a more streamlined interface:
	~Bumped "Community" up a section to be more noticeable. This section
	 encompasses artist's twitter accounts or websites, as well as website hubs and forums
	~Added a "Videos" section to the inspiration section
-Re-arranged the "Contents" section to match the new changes in organization

### CODE REVIEW

**Comment by rowtechshio** [comment]
Apologies for the mess of commits and updates. Every time I made a significant change in the Readme, in order to view it I recommitted it back into my forked repo.

**Comment by Siilwyn** [comment]
Awesome! Much appreciated! :heart: 

Two points:
- not a fan of the new pixel animations, I'd rather keep it minimalistic/clean with only text. The current animation at the top is an exception because it illustrates how pixel art looks and is made. Okay to remove those?
- unsure about the new games, could you create a separate PR for that?

Don't worry about the commits, I'll clean them up when I merge the changes. :)

**Comment by rowtechshio** [comment]
For sure, I'll take those out. I'm not sure what you mean by making a separate PR?

**Comment by Siilwyn** [comment]
Ah sorry I'm used to using GitHub lingo, I meant creating a new pull request with only the addition of the games. Created a new PR at https://github.com/Siilwyn/awesome-pixel-art/pull/17

I've merged your main changes at https://github.com/Siilwyn/awesome-pixel-art/pull/16! :confetti_ball:

**Pull request closed without merging**
