### PR TITLE
Added color tutorial and changed the Reddit thing

### PR DESCRIPTION
**Pull request by ninjamuffin99**
added to a neat color tutorial, and specified the reddit title to "Reddit /r/pixelart" in case there are other subreddits related to pixel art.

Also I organized the tutorial section, separating it into different categories of interest.

### CODE REVIEW

**Comment by Siilwyn** [comment]
Thank you, these are some great resources! :heart: 

I'm not sure about the tutorial categories though, the way I imagined it is a list sorted by specificity so newcomers can learn by reading from top to bottom. Categories can help but for example the outlining category should contain one awesome resource that covers all information instead of multiple resources that all miss something, right?

Maybe we can stick with no categories or go with something like:
- Basics
  - Introduction
  - Shapes
  - Outline
- Colors
- Animation

Thoughts?

**Comment by ninjamuffin99** [comment]
I think there should be some sort of categorization, for those who might be looking for a specific thing. But I do like the idea of it being sorted by specificity. I changed the formatting a bit

**Comment by Siilwyn** [comment]
Hey I flattened the categories a bit, I'd rather not have too many. Opened a PR in your fork.

**Comment by ninjamuffin99** [comment]
merged the PR

**Comment by Siilwyn** [comment]
Thank you for your contribution, I've invited you as collaborator: feel free to accept or decline.

**Pull request merged**
