### PR TITLE
Add make8bitart.com

### PR DESCRIPTION
**Pull request by mikker**

### CODE REVIEW

**Comment by Siilwyn** [comment]
Looks very cool though I would say [Piksel](http://www.piskelapp.com/) offers the same and more right?

**Comment by mikker** [comment]
@Siilwyn It probably does but I've never needed all that. I love Jenn's tool though `¯\_(ツ)_/¯`

**Comment by Siilwyn** [comment]
🤔 I try to prevent putting tools that are very similar, rather have a short list of the most awesome ones than a long list. Since Piskel also enables instantly drawing pixel art but with more features when needed I'm going to close this one. Thank you for your pull request though!

**Comment by mikker** [comment]
No problem – thanks for considering 👍🏻

**Pull request closed without merging**
