### PR TITLE
Added PixelCraft Editor

### PR DESCRIPTION
**Pull request by theabbie**
Added [PixelCraft](https://github.com/rgab1508/PixelCraft) Editor

### CODE REVIEW

**Comment by theabbie** [comment]
PixelCraft is a pixel Art & Animation Creation Tool Built using HTML5 Canvas.
It is a Progressive Web App (PWA) with offline compatibility.
It is mobile-friendly and is very easy to use.

**Comment by theabbie** [comment]
@Siilwyn

**Comment by Siilwyn** [comment]
Hello @theabbie  and thanks for your contribution! :zap:

This looks similar to Piksel which is also a webapp to try out pixel art.

Would love to replace Piksel in the list with PixelCraft since the latter seems to have stopped with maintenance in Q1 this year...

However I do notice some not-so awesome styling issues in Firefox:
image
The icons are not centered and the edges of the pixel art itself are blurry, the `canvas` element is missing `image-rendering: crisp-edges;` by the looks of it.

**Comment by theabbie** [comment]
@Siilwyn Yeah, I agree, It wasn't thoroughly tested on different browsers, It was developed mostly for chrome and PWA is best supported on chrome. Icon centering might be fixed. I tried `image-rendering: crisp-edges;` on canvas which somehow didn't work, It can be fixed by increasing the resolution of canvas, currently the resolution is 10 times the pixel dimensions, so, 16x16 pixel art will create 160x160 image/gif, I can change the scaling factor to 100 which will make it sharper and produce 100 times resolution. If you want that, I will do that.

**Comment by theabbie** [comment]
@Siilwyn I tested it at 100 scaling factor, which produces amazingly sharp images,

canvas (21)

But, 1600x1600 image might be too big for a 16x16 pixel art, might need to scale it down again.

**Comment by Siilwyn** [comment]
Hmmm, are you sure about that CSS property having no effect? It does for me, check out this article:
https://developer.mozilla.org/en-US/docs/Games/Techniques/Crisp_pixel_art_look

**Comment by theabbie** [comment]
@Siilwyn It worked for this? I tried adding that CSS property, I didn't see any noticeable difference in sharpness, anyways, it's open-source, if people feel like something can be changed, they can contribute. Don't you feel it can be added to this list as is for now and people can contribute later?

**Comment by theabbie** [comment]
@Siilwyn Oh, it worked, Wait, I will deploy it, I had to add all the 4 versions for cross-browser compatibility.

**Comment by theabbie** [comment]
@Siilwyn [This](https://pixelcraft.web.app) is the updated version, would love to hear your feedback.

**Comment by Siilwyn** [comment]
Looks sharp!

Would like to directly link to https://pixelcraft.web.app/ instead of the GH repo, since you mentioned people can contribute it might be worthwhile to link to the repository from the webpage?

**Comment by theabbie** [comment]
@Siilwyn Linking to Repository feels more trustworthy though, also, if at all the domain changes in future, it could be easily navigable from that Repo, The primary attraction should be open-source, so, I feel It should be linked to Repo.

**Comment by theabbie** [comment]
@Siilwyn Can we proceed with merging this?

**Comment by theabbie** [comment]
@Siilwyn can we?

**Comment by Siilwyn** [comment]
Merged!

**Comment by theabbie** [comment]
@Siilwyn Awesome, Thank you so much.

**Pull request merged**
